### ISSUE TITLE
Tables are not properly rendered on Javadoc hover

### ISSUE THREAD

**Issue by bonaluo** [redhat-developer/vscode-java#1002]
Issue Type: <b>Bug</b>

Doc cannot be displayed correctly
![image](https://user-images.githubusercontent.com/27731323/61848834-f6066680-aee1-11e9-9d4c-835819904358.png)
This should be a table.

Extension version: 0.47.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (4.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by fbricon** [comment]
Can you provide a sample project reproducing this? AFAIK, the markdown support in hover is pretty limited in vscode, I wouldn't be surprised if it was by design.

**Comment by bonaluo** [comment]
You can hover on java.util.concurrent.BlockingQueue.
![image](https://user-images.githubusercontent.com/27731323/61951628-20404d00-afe4-11e9-93e7-f3719a252c5b.png)

**Comment by fbricon** [comment]
Ok so I confirm vscode does support Markdown table syntax in typescript documentation, so that means jdt.ls returns really crappy Markdown for tables.

**Comment by fbricon** [comment]
@NikolasKomonen this might be tricky to fix as it's coming from remark directly, but you can take a look.

**Comment by fbricon** [comment]
Found https://github.com/giflw/remark-java/issues/9

**Comment by bonaluo** [comment]
But how to set it in vscode.

**Comment by fbricon** [comment]
@bonaluo you can't. This is an issue we need to fix in the Java language server

**Comment by bonaluo** [comment]
Thanks for your help.

**Comment by NikolasKomonen** [comment]
Check here for the updated remark library that should fix this issue: https://mvnrepository.com/artifact/com.kotcrab.remark/remark

**Comment by NikolasKomonen** [comment]
@fbricon, could you address if these issues need to be worked on/ indicate if some should be ignored.

### Issue 1) New lines are being removed from existing markdown tables. (Not an issue if we don't expect markdown in a javadoc)

Given:
```
| a | b |  
|---|---|  
| c | d |
```
JDT.ls returns:
```
| a | b | |---|---| | c | d |
```
when it should be returning
```
| a | b |\n|---|---|\n| c | d |
```

### Issue 2) HTML to Markdown returns incorrect markdown when the table headers are defined as:
```html
<table>
    <tr>
        <th>A</th>
        <th>B</th>
        <th>C</th>
    </tr>
    ...
</table>
```
The issue is that Remark requires the `<thead>` tag around the headers for it to consider the row
a header row. [Although HTML 5 doesn't require them](https://stackoverflow.com/questions/29111522/is-it-required-to-use-thead-tbody-and-tfoot-tags)
```html
<table>
    <thead>
        <tr>
            <th>A</th>
            <th>B</th>
            <th>C</th>
        </tr>
    </thead>
    ...
</table>
```

### Issue 3) Converted HTML to Markdown doesn't render properly

| Firstname | Lastname | Age |
| --------- | -------- | --- |
| Jill      | Smith    | 50  |
| Eve       | Jackson  | 94  |

What we're currently getting:
![jdtlsMarkdown](https://user-images.githubusercontent.com/32624665/63462113-321ce080-c428-11e9-9f0f-31c1099bbfa8.png)

JSON data from JDT.ls HTML to Markdown **(Doesn't Work)**:
```
    | Firstname | Lastname | Age |\n    | --------- | -------- | --- |\n    | Jill      | Smith    | 50  |\n    | Eve       | Jackson  | 94  |
```


JSON data from TS.ls HTML to Markdown **(Works)**:
```
| Firstname | Lastname | Age |\n| --------- | -------- | --- | \n| Jill      | Smith    | 50  |\n| Eve       | Jackson  | 94  |
```


**Solution:** The issue is JDT.ls or Remark (need to verify) is indenting with 4 spaces each new line. This
breaks the markdown table.

**Comment by fbricon** [comment]
We prolly want to fix all 3, but right now I'd love to see the exemple of java.util.concurrent.BlockingQueue be fixed. With remark 1.1.0, we still see crappy tables:
<img width="604" alt="Screen Shot 2019-08-22 at 5 33 11 PM" src="https://user-images.githubusercontent.com/148698/63528689-aaa49f80-c503-11e9-9e55-3eba6edc67e8.png">

**Comment by NikolasKomonen** [comment]
![FixedTables](https://user-images.githubusercontent.com/32624665/63615732-07f82980-c5b4-11e9-885b-5d72a7634692.png)

Table fixed. Need to do tests and get it uploaded to maven repo.

@fbricon Were there any other cases to test out, I remember you mentioned it.

**Comment by fbricon** [comment]
@NikolasKomonen  I can't remember other cases of Javadoc using tables, but since this @bonaluo's case is fixed, let's close this issue. Thanks!
