### ISSUE TITLE
Annoying Unable to get documentation under 500ms

### ISSUE THREAD

**Issue by hcorion** [redhat-developer/vscode-java#189]
I decided to update my language support for java today, and now in output, it spams
`[Error - 12:49:14 PM] Apr 20, 2017 9:20:26 AM Unable to get documentation under 500ms`
This is really annoying, and shouldn't be elevated to error, at most it should be warning. 

Maybe the rest of the world is on Fiber Optic, and I'm stuck with a measly 40 Mbps download.

##### Environment
- Operating System: Arch Linux 64-bit
- JDK version:1.8.0_121
- Visual Studio Code version: 1.11.2
- Java extension version: 0.2.0

**Comment by fbricon** [comment]
What can of project have you opened? Maven, Gradle, Eclipse? Or standalone file?
Could you paste the content of your .classpath?

I can see how it's annoying, I'll release a 0.2.1 fix tomorrow.

**Comment by hcorion** [comment]
@fbricon just a standalone file.

**Comment by fbricon** [comment]
Are you using OpenJDK?

**Comment by hcorion** [comment]
Yes

**Comment by fbricon** [comment]
Have you installed OpenJDK sources? If not, can you try it, that should fix the issue

**Comment by hcorion** [comment]
Just install openjdk 8 sources and restarted Vscode, issue still persists.

**Comment by fbricon** [comment]
@hcorion please try [installing](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) http://download.jboss.org/jbosstools/jdt.ls/staging/java-0.2.1-148.vsix

**Comment by hcorion** [comment]
Yes, appears to fix the issue, thanks!

**Comment by fbricon** [comment]
The 0.2.1 extension has been published to the VS Code Marketplace
