### ISSUE TITLE
The quickfix doesn't suggest the correct import type when the unresolved type is in an anonymous class 

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2034]
The quick fix does not provide a valid fix suggestion when the unresolved type is in an anonymous class. Here is the screenshot.

https://user-images.githubusercontent.com/14052197/126339936-f189f2be-474d-4878-8b3b-661349acd712.mov

_Originally reported by @@hasen6 at https://github.com/microsoft/vscode-java-pack/issues/691_

**Comment by snjeza** [comment]
This is an upstream issue. I can reproduce it in Eclipse  4.21 build I20210719-1800

**Comment by snjeza** [comment]
Related bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=574982

**Comment by snjeza** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=574982 has been fixed. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=574982#c10

**Comment by hasen6** [comment]
@testforstephen All the threads open regarding this issue seem to now be closed but the original bug in VSCode still exists. Am I to assume an update is forthcoming?

**Comment by testforstephen** [comment]
@hasen6 Yes, **Language Support for Java(TM) by Red Hat** extension will have a new version 0.81.0 to include this fix.

**Comment by hasen6** [comment]
@testforstephen Oh ok great, thanks.
