### ISSUE TITLE
Duplicate import on "Organize imports" action

### ISSUE THREAD

**Issue by CarlosAzocar** [redhat-developer/vscode-java#253]
Duplicate import on "Organize imports" action

##### Environment
- Operating System: Windows 10 x64
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.13.1
- Java extension version: 0.7.0

![step1](https://user-images.githubusercontent.com/18235355/27843139-a796fb70-60de-11e7-8207-26cb36334058.png)
![step2](https://user-images.githubusercontent.com/18235355/27843140-a79d7d74-60de-11e7-9d84-be27799f9c50.png)

**Comment by fbricon** [comment]
Can you provide a sample project to reproduce the problem?

cc @aeschli

**Comment by CarlosAzocar** [comment]
Project: https://github.com/CarlosAzocar/VinexJPA 
Line: 7 
File: RepositoryBase.java

**Comment by fbricon** [comment]
Thanks, I can reproduce the issue in vscode-java, but not in Eclipse. 

@aeschli do you mind taking this one?

**Comment by aeschli** [comment]
@fbricon Yes, please assign to me... (I don't have the rights to assign)

**Comment by fbricon** [comment]
@yaohaizh can you follow up on this one please?

**Comment by yaohaizh** [comment]
@fbricon  Sure. Please assign this to me.

**Comment by yaohaizh** [comment]
This should have been fixed in the latest VSCode java with change for organize imports.

**Comment by fbricon** [comment]
The issue is not reproducible when using the `Organize Imports` command, but is still present when calling the matching Code Action.

**Comment by yaohaizh** [comment]
Okay, it seems the code action still use the original TextEditConverter which will have issues for resolving. 

Any way,  I still confused why the code below will works for import but not works for other code actions.
```java
	/* (non-Javadoc)
	 * @see org.eclipse.text.edits.TextEditVisitor#visit(org.eclipse.text.edits.DeleteEdit)
	 */
	@Override
	public boolean visit(MoveSourceEdit edit) {
		try {
			org.eclipse.lsp4j.TextEdit te = new org.eclipse.lsp4j.TextEdit();
			te.setNewText("");
			te.setRange(JDTUtils.toRange(compilationUnit, edit.getOffset(), edit.getLength()));
			converted.add(te);
		} catch (JavaModelException e) {
			JavaLanguageServerPlugin.logException("Error converting TextEdits", e);
		}
		return super.visit(edit);
	}
```

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/commit/aa79b5733115374ac97a32aabcaab0c947a6fac8#diff-5443276e78beb5841951c89e7335cb6bR136
