### ISSUE TITLE
Broken autocomplete when writing in a new file in a new directory

### ISSUE THREAD

**Issue by rohanbari** [redhat-developer/vscode-java#3194]
The extension fails to work appropriately on creating a new file in a new directory. That is, it would not display suggestions further. I thought it was a user-end problem. I tried reinstalling the extension. Yet, it persisted.

##### Environment
- Operating System: Linux Mint 21.1 Vera
- JDK version: javac 17.0.7
- Visual Studio Code version: 1.80.0
- Java extension version: v1.20.0 (Language Support for Java by RedHat)

##### Steps To Reproduce

1. Open Code with the extensions enabled
2. Create a new file in a new directory
3. Start writing code

##### Image version of the misbehavior

![Problem Image](https://github.com/redhat-developer/vscode-java/assets/54104015/8314ae15-67cf-414c-8c0a-faac501f68fc)

<sup>* I don't think it needs a text version here.</sup>

**Edit:** The problem goes away on an app restart.

##### Java Extension Logs

[Logs here](https://pastebin.com/hftgUA6L)

To ease dev work, my intuition says the problems are logged from line no. 19732-'37:

```
!ENTRY org.eclipse.jdt.ls.core 4 0 2023-07-11 19:09:12.705
!MESSAGE Error occured while building workspace. Details: 
 message: Syntax error, insert ";" to complete BlockStatements; code: 1610612976; resource: /home/rohan/code/java-lang/src/mathematics/FibonacciSeries.java; line: 6
 message: sout cannot be resolved; code: 570425394; resource: /home/rohan/code/java-lang/src/mathematics/FibonacciSeries.java; line: 6
 message: Syntax error, insert "VariableDeclarators" to complete LocalVariableDeclaration; code: 1610612976; resource: /home/rohan/code/java-lang/src/mathematics/FibonacciSeries.java; line: 6
```

##### Expected Result

Anyone would expect some suggestion to appear.

##### Additional Information

Well, I know contributing is fun.
At this moment in my life, I have no idea what additional information to provide. But yeah, I can say it works correctly sometimes, very unpredictable.

**Comment by testforstephen** [comment]
I also encountered this issue a few times. No intellisense in the new Java file. Usually reloading the window can fix it.

**Comment by snjeza** [comment]
This is an upstream VS Code issue. I can't reproduce it in VS Code <= 1.79.2.
It is reproducible in VS Code 1.80.0 and code-insiders

**Comment by starball5** [comment]
Related on Stack Overflow:

- [My VScode intellisense not working in my java project](https://stackoverflow.com/q/76646095/11107541)
- [Intellisense only works if i create a new project](https://stackoverflow.com/q/76641794/11107541)
- [VSCode Java Automcomplete Issues](https://stackoverflow.com/q/76631184/11107541)
- [VSC don't work after update from Java 17 to 20](https://stackoverflow.com/q/76594445/11107541)
- [Visual Studio Code does not give suggestions or autocompletion when creating a new file](https://stackoverflow.com/q/76650595/11107541)
- [My VS Code is unable to display sout as System.out.println for new java files that I make](https://stackoverflow.com/q/76656023/11107541)
- [Intellisense in VS code for java is only working if I enable and disable extensions when I create a new file](https://stackoverflow.com/q/76667593/11107541)

**Comment by starball5** [comment]
Quoting from [my answer post on Stack Overflow](https://stackoverflow.com/a/76668212/11107541):

Upon further inspection, I found this issue ticket in the VS Code repo: [Are choice snippets dangerous now? Breaking extensions completions #187642](https://github.com/microsoft/vscode/issues/187642), where there has been a regression with choice snippets from commit [`3e232a8`](https://github.com/microsoft/vscode/commit/3e232a82df4313fb8ca898471416763288c6827d). Notably, if you look in [the release notes for the Red Hat Java Language Support extension, the 1.20.0 section](https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#1200-june-29th-2023) says:

> - enhancement - Use choice syntax as placeholder for constructor/method/field snippets. See [#3018](https://github.com/redhat-developer/vscode-java/pull/3018), [#3140](https://github.com/redhat-developer/vscode-java/pull/3140).

**Comment by testforstephen** [comment]
@starball5 Great comment, thanks for the information.

**Comment by testforstephen** [comment]
> With latest Insider which is 1.81.0 it seems to work.

It works for me as well when I use the `vscode@1.81.0-insider (2023-07-12)` version.

**Comment by testforstephen** [comment]
Close it since this issue has been fixed in the latest `vscode@1.80.1` version.

**Comment by ChefAharoni** [comment]
Hey, 

I'm still having this issue.
My VS Code is updated, I tried uninstalling the Java Extension pack, restarting all extensions, cleaning the workspace, restarting VS Code, and restarting Java Language Server.

Any guidance on how to solve this?
