### ISSUE TITLE
The method builder() is undefined for the type xxx

### ISSUE THREAD

**Issue by f425** [redhat-developer/vscode-java#3733]
# [demo](https://github.com/f425/project-for-test/tree/lombok-comment)

## env
* Windows 10
* JAVA_HOME: `C:\Program Files\Java\jdk1.8.0_202`
* Extension: Pack for Java v0.27.0
* Extension: Language Support for Java(TM) by Red Hat v1.33.0
* Extension: Gradle for Java v3.16.1
* jdk1.8.0_202 from Oracle
* jdk-17.0.12+7 from Adoptium
* lombok v1.18.12
* vscode Version: 1.92.0
* vscode config `setting.json` about java and gradle:
    1. `C:\\Program Files\\Java\\jdk1.8.0_202` (Oracle jdk8 for code project)
    2. `C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.12+7` (for vscode language server)
    ```json
        {
            "java.jdt.ls.java.home": "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.12+7",
            "java.import.gradle.java.home": "C:\\Program Files\\Java\\jdk1.8.0_202",
            "java.configuration.runtimes": [
                {
                    "name": "JavaSE-1.8",
                    "path": "C:\\Program Files\\Java\\jdk1.8.0_202",
                    "default": true
                }
            ]
        }
    ```

## problem
1. after upgrade `Extension: Language Support for Java(TM) by Red Hat` to `v1.33.0`.  Got error:
```
[{
	"resource": "/c:/Users/ww/work/test/project-for-test/test2/src/main/java/com/test2/Test2.java",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": "67108964",
	"severity": 8,
	"message": "The method builder() is undefined for the type Data1",
	"source": "Java",
	"startLineNumber": 9,
	"startColumn": 15,
	"endLineNumber": 9,
	"endColumn": 22
}]
```
2. Change `Extension: Language Support for Java(TM) by Red Hat` to `v1.32.0`. It's OK.
3. Keep `Extension: Language Support for Java(TM) by Red Hat` with `v1.33.0`.
    * copy `Data1.java` to `Data2.java` and delete comments.
    * `Data2.builder().build()` is ok

![image](https://github.com/user-attachments/assets/2a4576c1-b84c-4ea8-b463-2bfaa733728e)

**Comment by heguro** [comment]
There seem to be several issues related to the Javadoc comments of the `@Builder` class in the latest Lombok 1.18.34. ([issue 1](https://github.com/projectlombok/lombok/issues/3706), [issue 2](https://github.com/projectlombok/lombok/issues/3709))

The version of Lombok bundled in this extension is [from](https://github.com/redhat-developer/vscode-java/pull/3674) `https://projectlombok.org/lombok-edge.jar`, which currently delivers the same binary as Lombok 1.18.34, thereby affecting this extension.

Temporary solutions I discovered:

- Downgrade this extension to v1.32.0
- Or use the `lombok/lombok-1.18.33.jar` bundled in v1.32.0
  - Overwrite the jar file in the same path of the current version, or [build and install](https://github.com/redhat-developer/vscode-java/issues/3561#issuecomment-2134008540) the `.vsix` file yourself

<details>
<summary>Steps to overwrite</summary>

Windows PowerShell environment:
```ps1
# Get and extract vscode-java v1.32.0 binary
curl.exe -LO "https://github.com/redhat-developer/vscode-java/releases/download/v1.32.0/vscode-java-1.32.0-220.vsix"
Rename-Item "vscode-java-1.32.0-220.vsix" "vscode-java-1.32.0-220.vsix.zip"
Expand-Archive -Path ".\vscode-java-1.32.0-220.vsix.zip" -DestinationPath ".\temp_ext"

# Copy .jar file
Copy-Item "temp_ext/extension/lombok/lombok-1.18.33.jar" "$env:userprofile/.vscode/extensions/redhat.java-1.33.0-win32-x64/lombok/lombok-1.18.33.jar"

# Remove downloaded files
Remove-Item -Recurse -Path "temp_ext","vscode-java-1.32.0-220.vsix.zip"
```

WSL/Docker environment:
```sh
# Get and extract vscode-java v1.32.0 binary
curl -LO https://github.com/redhat-developer/vscode-java/releases/download/v1.32.0/vscode-java-1.32.0-220.vsix
# or wget:
# wget https://github.com/redhat-developer/vscode-java/releases/download/v1.32.0/vscode-java-1.32.0-220.vsix
unzip -d temp_ext/ vscode-java-1.32.0-220.vsix

# Copy .jar file
cp temp_ext/extension/lombok/lombok-1.18.33.jar /home/$(whoami)/.vscode-server/extensions/redhat.java-1.33.0*/lombok/lombok-1.18.33.jar

# Remove downloaded files
rm -rf /tmp/temp_ext vscode-java-1.32.0-220.vsix
```

</details>

**Comment by f425** [comment]
@heguro 
Lombok` version is `1.18.12` in my demo project.
Before this extension v1.33.0,  it was working fine.

**Comment by f425** [comment]
![image](https://github.com/user-attachments/assets/ca9b459c-a059-4639-98bc-6123ad57e281)
![image](https://github.com/user-attachments/assets/6baa8012-121d-48a2-b87a-a6fefeefd76f)
![image](https://github.com/user-attachments/assets/3edc2a69-1a9b-4c6f-8b0c-897eb9190e13)

**Comment by iwangbowen** [comment]
Is it fixed in the latest version

**Comment by foxpluto** [comment]
Which version are you referring? I have the Language Support for Java(TM) by Red Hat v1.35.202408 and the bug is still there.

**Comment by iwangbowen** [comment]
when this will be fixed

**Comment by Kas-tle** [comment]
Lombok has merged a fix as of a few days ago (see  https://github.com/projectlombok/lombok/pull/3726), but they have not done a release yet. So I assume that will have to happen first so that an updated version of Lombok can be bundled with the extension.

**Comment by rgrunber** [comment]
https://github.com/redhat-developer/vscode-java/issues/3561#issuecomment-2442023671 woke me up. Could someone try the vscode-java pre-release and see if the problem is resolved ? According to  https://github.com/redhat-developer/vscode-java/blob/0f89a67eaf7a0189e3da172a02e277d128a96cc7/gulpfile.js#L132 (the 1.18.33 label we give is wrong, but it's definitely the latest), we're using the latest lombok edge release, which is from 2024-10-18. That definitely should have the fix. If it doesn't work then the problem was never fixed by the PR.

**Comment by NicoFraenzel** [comment]
With the currently used Lombok v1.18.34 this is still an issue. Updating to v1.18.36 should fix it (relevant commit: https://github.com/projectlombok/lombok/commit/1ac3950a9e8d1c2da0ff0d6400386a9b345b23a2). At least it did so for the Eclipse IDE.
