### ISSUE TITLE
[BUG]string array equals a string was not captured by compiler as a problem ,while failed to compile the class.

### ISSUE THREAD

**Issue by zheddie** [redhat-developer/vscode-java#4020]
**OS:** 
Windows 10 22H2,   

**VSCode:** 
Version: 1.98.2
Commit: ddc367ed5c8936efe395cffeec279b04ffd7db78
Date: 2025-03-12T13:32:45.399Z
Electron: 34.2.0
ElectronBuildId: 11161602
Chromium: 132.0.6834.196
Node.js: 20.18.2
V8: 13.2.152.36-electron.0
OS: Windows_NT x64 10.0.19045

**Plugin of Java: Extension Pack of Java**
Identifier
vscjava.vscode-java-pack
Version
0.29.0
Last Updated
2025-04-03, 17:05:41

**Code to reproduce the issue:**

```
package com.zg.bugs;
import java.lang.String;

public class StringArrayEqualsString{
    public  static void main(String[] args){
        String[] sss = {"aa","bb"};
        String sts = "cc";
        if(sss.equals(sts)){
            System.out.println("ERROR!");
        }else{
            System.out.println("DONE!");
        }
        return;
    }
}
```
**Description:**
when we use a string array (sss in the code) to do the equals() routine on a string (sts), this file would be failed to compile , while the vscode IDE didn't report any error or problem. This would cause the developer consume too much time to identify , as no any problem was reported, while the class was not successfully copmile out.  

Anybody can help to fix it ? thanks.

**Comment by snjeza** [comment]
This is an upstream [jdt.core](https://github.com/eclipse-jdt/eclipse.jdt.core) - https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3870
I can reproduce the issue with VS Code 1.41.1 and pre-release.
@zheddie You can try VS Code 1.41.0

**Comment by zheddie** [comment]
hmmm. do you mean 1.99.0?  which is the latest so far. @snjeza

**Comment by rgrunber** [comment]
1.41.0 / 1.41.1 is a reference to the [version of vscode-java](https://github.com/redhat-developer/vscode-java/releases). The upstream label is referring not to the VS Code editor itself, but the upstream of one of our dependencies. @snjeza , the issue is closed and the jdt-core-incubator is already rebased on the referenced PR. Would this just be fixed after a rebuild in vscode-java pre-releases ?

**Comment by snjeza** [comment]
> Would this just be fixed after a rebuild in vscode-java pre-releases ?

Yes, it will be fixed.  I can't reproduce the issue using the Java LS main branch.

**Comment by rgrunber** [comment]
Yup, here's the error spit out in the logs :

```
[Error - 13:07:40] Apr 7, 2025, 1:07:40 p.m. Exception occurred during problem detection:
----------------------------------- SOURCE BEGIN -------------------------------------
package com.zg.bugs;
import java.lang.String;

public class StringArrayEqualsString{
    public  static void main(String[] args){
        String[] sss = { "aa", "bb" };
        String sts = "cc";
        if(sss.equals(sts)){
            System.out.println("ERROR!");
        }else{
            System.out.println("DONE!");
        }
        return;
    }
}
----------------------------------- SOURCE END -------------------------------------
Cannot read field "id" because "type1" is null
java.lang.NullPointerException: Cannot read field "id" because "type1" is null
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.hasEqualsMethodInCommonSuperType(UnlikelyArgumentCheck.java:81)
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.hasEqualsMethodInCommonSuperType(UnlikelyArgumentCheck.java:91)
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.isDangerous(UnlikelyArgumentCheck.java:74)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:158)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.analyseCode(IfStatement.java:71)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:160)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:1011)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:321)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:127)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:978)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1017)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:292)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:358)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:243)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:108)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:751)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:816)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1430)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:338)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:301)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:798)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

If I build from source though, with the latest I-build, the error is gone and the code runs. So it will be part of the next pre-release build, and fixed in the 1.42.0 release (end of month).

**Comment by Mike-the-one** [comment]
Problem still exists in 1.42.0 java language server.  Downgrade to 1.40.0 fixed the issue

**Comment by rgrunber** [comment]
> Problem still exists in 1.42.0 java language server. Downgrade to 1.40.0 fixed the issue

Works for me on vscode-java 1.42.0 :

![Image](https://github.com/user-attachments/assets/c32fcd57-31db-4d69-bbde-00ae7c5db16a)

Do you have a sample of it not working ?

**Comment by Mike-the-one** [comment]
Here is the log

```sh
[Error - 8:37:52 AM] Jun 3, 2025, 8:37:52 AM Exception occurred during problem detection:
----------------------------------- SOURCE BEGIN -------------------------------------
package com.abc;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_NULL)
public class UPSDc {

    public static String SIGNATURE_TYPE_REQUIRED = "2";
    public static String SIGNATURE_TYPE_ADULT_REQUIRED = "3";

    boolean state;

    String type;

    public UPSDc() {
    }

    public UPSDc(boolean state, String type) {
        this.state = state;
        this.type = type;
    }

    public boolean getState() {
        return this.state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Dc)) {
            return false;
        }
        Dc dc = (Dc) o;
        return Objects.equals(state, dc.state) && Objects.equals(type, dc.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(state, type);
    }

    @Override
    public String toString() {
        return "{" + " state='" + getState() + "'" + ", type='" + getType() + "'" + "}";
    }

}
----------------------------------- SOURCE END -------------------------------------
Cannot read field "id" because "type1" is null
java.lang.NullPointerException: Cannot read field "id" because "type1" is null
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.hasEqualsMethodInCommonSuperType(UnlikelyArgumentCheck.java:83)
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.hasEqualsMethodInCommonSuperType(UnlikelyArgumentCheck.java:93)
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.isDangerous(UnlikelyArgumentCheck.java:76)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:167)
	at org.eclipse.jdt.internal.compiler.ast.AND_AND_Expression.analyseCode(AND_AND_Expression.java:62)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.analyseCode(ReturnStatement.java:101)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:160)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:874)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:314)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:127)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:978)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1017)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:292)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:358)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:243)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:108)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:751)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:816)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1431)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:338)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:301)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:798)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rgrunber** [comment]
I see it as well with this code.

<details>
<summary>stacktrace</summary>

```
[Error - 08:59:46] Jun 3, 2025, 8:59:46 a.m. Exception occurred during problem detection:
----------------------------------- SOURCE BEGIN -------------------------------------
package com.abc;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(Include.NON_NULL)
public class UPSDc {

    public static String SIGNATURE_TYPE_REQUIRED = "2";
    public static String SIGNATURE_TYPE_ADULT_REQUIRED = "3";

    boolean state;

    String type;

    public UPSDc() {
    }

    public UPSDc(boolean state, String type) {
        this.state = state;
        this.type = type;
    }

    public boolean getState() {
        return this.state;
    }

    public void setState(boolean state) {
        this.state = state;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this)
            return true;
        if (!(o instanceof Dc)) {
            return false;
        }
        Dc dc = (Dc) o;
        return Objects.equals(state, dc.state) && Objects.equals(type, dc.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(state, type);
    }

    @Override
    public String toString() {
        return "{" + " state='" + getState() + "'" + ", type='" + getType() + "'" + "}";
    }

}
----------------------------------- SOURCE END -------------------------------------
Cannot read field "id" because "type1" is null
java.lang.NullPointerException: Cannot read field "id" because "type1" is null
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.hasEqualsMethodInCommonSuperType(UnlikelyArgumentCheck.java:83)
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.hasEqualsMethodInCommonSuperType(UnlikelyArgumentCheck.java:93)
	at org.eclipse.jdt.internal.compiler.ast.UnlikelyArgumentCheck.isDangerous(UnlikelyArgumentCheck.java:76)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:167)
	at org.eclipse.jdt.internal.compiler.ast.AND_AND_Expression.analyseCode(AND_AND_Expression.java:62)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.analyseCode(ReturnStatement.java:101)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.analyseCode(MethodDeclaration.java:160)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.internalAnalyseCode(TypeDeclaration.java:874)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.analyseCode(TypeDeclaration.java:314)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.analyseCode(CompilationUnitDeclaration.java:127)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:978)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1017)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:292)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:358)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:243)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:108)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:751)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:816)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1431)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:338)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler.publishDiagnostics(BaseDocumentLifeCycleHandler.java:301)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseDocumentLifeCycleHandler$PublishDiagnosticJob.run(BaseDocumentLifeCycleHandler.java:798)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

</details>

In fact, I can even get (a more simplified) sample failing in Eclipse.

![Image](https://github.com/user-attachments/assets/21efccd3-5b11-4851-ba73-2c9e4c8558ee)
