### ISSUE TITLE
package does not exist

### ISSUE THREAD

**Issue by kasheemlew** [redhat-developer/vscode-java#546]
[provide a description of the issue]

##### Environment
- Operating System: macos sierra
- JDK version: 1.8
- Visual Studio Code version: 1.23.1
- Java extension version: 0.25.0

##### Steps To Reproduce
1. download  https://github.com/redhat-developer/vscode-java/files/1500211/test_vs_code2.zip
2. unzip test_vs_code2.zip
3. open test_vs_code with vscode

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

Got some warnings. `import` says "package org.json does not exist", `JSONObject` says "cannot find symbol", 
 
![image](https://user-images.githubusercontent.com/14333766/40793972-75ed65b2-6530-11e8-980a-91ba786e49b1.png)

##### Expected Result

such warnings should disappear

**Comment by kasheemlew** [comment]
Sorry to bother, it's due to another plugin

**Comment by wenfengsui** [comment]
Duplicate of #161 
try removing the java linter extension

**Comment by samuelAle** [comment]
I had this problem even without java linter extension ever having been installed.

I fixed the issue by reinstalling several java related extensions including the Java-Extension-Pack

**Comment by barisbt** [comment]
> Duplicate of #161
> try removing the java linter extension

Disabling Java Linter extension solved my problem, too.

**Comment by bitcoder** [comment]
Disabling Java Linter extension solved my problem, too.

**Comment by phlbrz** [comment]
Disabling Java Linter extension faustinoaq.javac-linter https://marketplace.visualstudio.com/items?itemName=faustinoaq.javac-linter solved for me!

**Comment by MungaiVic** [comment]
I removed the netbeans extension on my case and it got rid of the errors I was having. I don't understand why it caused those errors(plus false linting messages) but it worked.

**Comment by Nghiauet** [comment]
Thanks I fixed it by remove all extensions relate to java and re install
![image](https://github.com/redhat-developer/vscode-java/assets/63385521/e0f7662a-6521-430e-864d-b515d5b4c9be)

**Comment by Peter-E22** [comment]
I still have this problem Idk what could have gone wrong. All I did was create a new folder in the project itself and moved two files that use the correct package names into that folder and all of a sudden, the compiler says that the package<name of package> does not exist even after importing all packages as stated by the program
